#version 450

layout(local_size_x = 16, local_size_y = 16) in;

// Struct definition --------------------------------------------

struct HitData {
  vec4 wo;
  vec4 wi;
  vec4 hit;
  vec4 normal;
  vec4 color;
  uint depth;
};

struct PRNG32 {
    uvec4 state;
    float value;
};

// Bindings ------------------------------------------------------

layout(set=0,binding = 0) uniform ViewProj {
  mat4 view;
  mat4 proj;
} view_proj;


layout(std430, set = 0, binding = 1) buffer PixelData {
    HitData hit_data[];
};

layout(rgba8, binding = 2) uniform image2D StorageImage;

layout(std430, set = 0, binding = 3) buffer RNGBuffer{
    PRNG32 prng32[];
};

layout( push_constant ) uniform constants{
  vec4 test_color;
  int rpp;
} PushConstants;

// Functions ----------------------------------------------------


uint TausStep(uint z, int S1, int S2, int S3, uint M)
{
    uint b = (((z << S1) ^ z) >> S2);
    return (((z & M) << S3) ^ b);    
}

uint LCGStep(uint z, uint A, uint C)
{
    return (A * z + C);    
}

float random(inout PRNG32 rng)
{
    rng.state.x = TausStep(rng.state.x, 13, 19, 12, 4294967294);
    rng.state.y = TausStep(rng.state.y, 2, 25, 4, 4294967288);
    rng.state.z = TausStep(rng.state.z, 3, 11, 17, 4294967280);
    rng.state.w = LCGStep(rng.state.w, 1664525, 1013904223);

    rng.value = 2.3283064365387e-10 * (rng.state.x ^ rng.state.y ^ rng.state.z ^ rng.state.w);

    return rng.value;
}

// Main ---------------------------------------------------

void main() {
    uvec2 gid = gl_GlobalInvocationID.xy;
    ivec2 imageSize = imageSize(StorageImage);
    uint index = gid.y * imageSize.x + gid.x;


    PRNG32 rng = prng32[index];
    float c0 = random(rng);
    float c1 = random(rng);
    float c2 = random(rng);



    ivec2 pos = ivec2(gid);
    ivec2 center = imageSize / 2;
    vec4 color = vec4(0.0, 0.0, 0.0, 1.0); 
    ivec2 delta = pos - center;
    //if (dot(delta, delta) <= 100 * 100) {
    	color = hit_data[index].color;
       //color = vec4(c0,c1,c2,1.0);
    //}


    hit_data[index].depth += 1;
    prng32[index] = rng;
    imageStore(StorageImage, pos, color);
}
