#version 450

layout(local_size_x = 16, local_size_y = 16) in;

// Constant data definition ------------------------------------

const float EPSILON = 1e-5;

const float MAX_FLOAT = 3.4028235e38;
const float MIN_FLOAT = -3.4028235e38;

const uint null_shape   =  0x00000000u;
const uint plane_shape  =  0x00000001u;
const uint sphere_shape =  0x00000010u;

const uint null_material = 0x00000000u;

// Struct definition -------------------------------------------

struct HitData {
  vec4 wo;
  vec4 hit;
  vec4 normal;
  uint depth;
  float t;
};

struct PRNG32 {
    uvec4 state;
    float value;
};

struct Sphere{
    vec4 center;
    float radius;
};

struct Plane{
  vec4 center;
  vec4 edge1;
  vec4 edge2;
  float u;
  float v;
};
// Bindings ----------------------------------------------------

layout(set=0,binding = 0) uniform Camera {
  mat4 view;
  vec4 pos;
  float vp_dist;
} camera;


layout(std430, set = 0, binding = 1) buffer PixelData {
    HitData hit_data[];
};

layout(rgba8, binding = 2) uniform image2D StorageImage;

layout(std430, set = 0, binding = 3) buffer RNGBuffer{
    PRNG32 prng32[];
};


layout(std430, set = 0, binding = 4) buffer SpheresBuffer{
    Sphere spheres[];
};


layout(std430, set = 0, binding = 5) buffer PlanesBuffer{
    Plane planes[];
};

layout( push_constant ) uniform constants{
  uint rpp;
  uint numSpheres;
  uint numPlanes;
  uint numLights;
} PushConstants;

// Functions ---------------------------------------------------

uint TausStep(uint z, int S1, int S2, int S3, uint M)
{
    uint b = (((z << S1) ^ z) >> S2);
    return (((z & M) << S3) ^ b);    
}

uint LCGStep(uint z, uint A, uint C)
{
    return (A * z + C);    
}

float random(inout PRNG32 rng)
{
    rng.state.x = TausStep(rng.state.x, 13, 19, 12, 4294967294);
    rng.state.y = TausStep(rng.state.y, 2, 25, 4, 4294967288);
    rng.state.z = TausStep(rng.state.z, 3, 11, 17, 4294967280);
    rng.state.w = LCGStep(rng.state.w, 1664525, 1013904223);

    rng.value = 2.3283064365387e-10 * (rng.state.x ^ rng.state.y ^ rng.state.z ^ rng.state.w);

    return rng.value;
}

// Object intersection and shading -----------------------------

bool intersectionTest(in Plane plane, out float t ,inout HitData hd){
	//TODO provisory ...

	vec3 e1 = plane.edge1.xyz;
	vec3 e2 = plane.edge2.xyz;
	vec3 center = plane.center.xyz;
	vec3 rayOrigin = hd.hit.xyz;
	vec3 rayDir = hd.wo.xyz;

	vec3 normal = normalize(cross(e1, e2));
	float denom = dot(normal, rayDir);

    if (abs(denom) < EPSILON)
        return false; // Ray is parallel to the plane

    t = dot(center - rayOrigin, normal) / denom;

    if (t < 0.0)
        return false; // Intersection is behind the ray

    vec3 hit = rayOrigin + t * rayDir;
    vec3 local = hit - center;

    float u = dot(local,e1); 
    float v = dot(local,e2);

    if (abs(u) > plane.u * 0.5 || abs(v) > plane.v * 0.5){
        return false;
	}

    return true;
}

void fillHitData(in Plane plane,inout HitData hd){}

bool Trace(inout HitData hd){
	uint nearestIndex = 0;
	uint nearestShape = null_shape;
	float nearestT = MAX_FLOAT;
	const uint max_iterations = max(PushConstants.numSpheres,PushConstants.numPlanes);

	for(uint i = 0; i <max_iterations;++i){
		if(i < PushConstants.numPlanes){
			float hit_t;
			bool does_hit= intersectionTest(planes[i],hit_t,hd);
			if(does_hit && hit_t < nearestT){
				nearestT = hit_t;
				nearestIndex = i;
				nearestShape = plane_shape;
			}
		}
		//Next one
	}

	if(nearestShape == null_shape){
		return false;
	}

	else if(nearestShape == plane_shape){
		fillHitData(planes[nearestIndex],hd);
	}
	return bool(nearestShape);
}

// Main --------------------------------------------------------

void main() {
    uvec2 gid = gl_GlobalInvocationID.xy;
    ivec2 imageSize = imageSize(StorageImage);
    uint index = gid.y * imageSize.x + gid.x;


    PRNG32 rng = prng32[index];
    float c0 = random(rng);
    float c1 = random(rng);
    float c2 = random(rng);



    ivec2 pos = ivec2(gid);
    ivec2 center = imageSize / 2;
    vec4 color = vec4(0.0, 0.0, 0.0, 1.0); 
    ivec2 delta = pos - center;
    //if (dot(delta, delta) <= 100 * 100) {
    	//color = hit_data[index].color;
	//color = vec4(camera.vp_dist,camera.vp_dist,camera.vp_dist,0.0);
	//color = vec4(0.0,0.0,0.0,1.0);
       //color = vec4(c0,c1,c2,1.0);
	   color = vec4(camera.pos.x,camera.pos.y,camera.pos.z,1.0);
    //}


    hit_data[index].depth += 1;
    prng32[index] = rng;
    imageStore(StorageImage, pos, color);
}
